[package]
name = "ansi-pretty-print"
version = "0.0.2"
edition = "2024"
license = "MIT"
description = "Pretty-printing structured data with ANSI color support and ligatures. Mostly used for debug outputs."
repository = "https://github.com/piot/ansi-pretty-print"

[dependencies]
# tinter ="0.1.0" // TODO: Maybe use tinter in the future?
